#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

rm -fr types
yarn tsc -p jsconfig.json --noEmit false --declaration --emitDeclarationOnly --outDir types
cp -R ./src/types ./types/types
git add types
